<?php

$serverName ="HERCULES";
$connectionInfo = array( "Database"=>"calidad", "UID"=>"sa", "PWD"=>"Sky2022*!");
$conexion =sqlsrv_connect ($serverName, $connectionInfo);

$ORDEN = $_POST['ORDEN'];
$EQUIPO = $_POST['EQUIPO'];

$TIPO_DE_MANTENIMIENTO = $_POST['TIPO_DE_MANTENIMIENTO'];
$FECHA = $_POST['FECHA'];
$SERVICIO = $_POST['SERVICIO'];
$TIEMPO_EMPLEADO = $_POST['TIEMPO_EMPLEADO'];  
$RESPONSABLE = $_POST['RESPONSABLE'];
$FECHA_PROGRAMACION = $_POST['FECHA_PROGRAMACION'];
$FECHA_DE_ENTREGA = $_POST['FECHA_DE_ENTREGA'];
$TRABAJO_EJECUTADO = $_POST['TRABAJO_EJECUTADO'];  
$TIEMPO_EMPLEADO_FIN = $_POST['TIEMPO_EMPLEADO_FIN']; 
$OBSERVACION = $_POST['OBSERVACION']; 
$VALOR_REPUESTO = $_POST['VALOR_REPUESTO']; 


$sql="UPDATE MANTENIMIENTO SET FECHA_DE_ENTREGA='$FECHA_DE_ENTREGA',TIEMPO_EMPLEADO='$TIEMPO_EMPLEADO',TRABAJO_EJECUTADO='$TRABAJO_EJECUTADO',TIEMPO_EMPLEADO_FIN='$TIEMPO_EMPLEADO_FIN',OBSERVACION='$OBSERVACION',VALOR_REPUESTO='$VALOR_REPUESTO' WHERE ORDEN='$ORDEN'";
$query=sqlsrv_query($conexion,$sql);

    if($query){
        Header("Location: index2.php");
    }
?>